### ISSUE TITLE
Update Readme with better install instructions

### ISSUE THREAD

**Issue by kiikoh** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#1]
It should say 

"git clone https://github.com/Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance.git"
then "pip install xxx"
then "python Bot"

It should be as simple as being able to just copy and paste everything you tell it to then it works....

**Comment by santteegt** [comment]
@Roibal I can work on an easiest way to install & run your experiments.

**Comment by Roibal** [comment]
@kiikoh thank you for the suggestion. I have updated the installation instructions to include your description (plus a couple additions), please tell me if anything needs to be added. @santteegt please let me know if you would like to add additional info.

**Comment by Roibal** [comment]
I have edited the installation instructions, included (and modified) your instructions, and I will continue to modify the readme as project grows. If anyone has any future mods to readme, fork the repo and them submit your changes under a pull request and I will include. Thank you to everyone for helping to make this code better and better.

**Comment by Roibal** [comment]
Hi All - here is a step-by-step installation instruction to get my bots (and python-binance) installed. 

https://www.youtube.com/watch?v=u7ZOQar5V7w
