### ISSUE TITLE
save_historic_klines_csv files with wrong time information

### ISSUE THREAD

**Issue by apneef** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#15]
The save files wich are saved by save_historic_klines_csv have a wrong time format in the files.

The file contains the following line(s):
<module 'time' (built-in)>, 2e-05, 2e-05, 2e-05, 2e-05, 53.0

The line 262 in save_historical_data_Roibal.py :
            format_kline = "{}, {}, {}, {}, {}, {}\n".format(time, open1, High, Low, Close, Volume)
has to be:
            format_kline = "{}, {}, {}, {}, {}, {}\n".format(time1, open1, High, Low, Close, Volume)

**Comment by Roibal** [comment]
I fixed this section of the code and gave you credit. Thank you very much my friend.
