### ISSUE TITLE
Cannot run Triangle Arb Bot

### ISSUE THREAD

**Issue by mstofflett** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#19]
I've setup my server like this
yum install python-pip
git clone https://github.com/Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance.git
git clone https://github.com/Roibal/python-binance.git
pip install ccxt

copied BinanceTriArbTrader.py to the examples folder
ran 'python BinanceTriArbTrader.py'

got:

Traceback (most recent call last):
  File "BinanceTriArbTrader.py", line 31, in <module>
    from binance.client import Client
  File "/home/triangle/python-binance/examples/binance/client.py", line 8, in <module>
    from .helpers import date_to_milliseconds, interval_to_milliseconds
  File "/home/triangle/python-binance/examples/binance/helpers.py", line 3, in <module>
    import dateparser
ImportError: No module named dateparser

**Comment by Roibal** [comment]
It may be best to install all files within the Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance to the python-binance/examples/ folder rather than just moving the specific file itself. Additionally, after you have placed these files in the /examples/ folder, pip install python-binance , and this will fix your issues.

**Comment by Roibal** [comment]
Here is a vid where I go through the installation on Windows, I know you are using Linux but it may be helpful to follow a similar process: https://www.youtube.com/watch?v=u7ZOQar5V7w

**Comment by Roibal** [comment]
Also dateparser is just a standard library (i believe), i don't know why you would receive this error. Are you using Python 3 ?
