### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

### ISSUE THREAD

**Issue by wioym** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#20]
When you get this issue to download the Visual Studio Installer:
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
If you are from the far away future and the above link doesn't work, just google Visual Studio Installer. 

Under Workloads select Desktop development with C++: 
![image](https://user-images.githubusercontent.com/24494206/49662162-65127600-fa4b-11e8-9542-6d34d8fe7539.png)

Also, select python under Web&Cloud:
![image](https://user-images.githubusercontent.com/24494206/49662254-95f2ab00-fa4b-11e8-9e9e-2fc4d2cec965.png)

Lastly, I've installed Windows 10 SDK:
![image](https://user-images.githubusercontent.com/24494206/49662333-c76b7680-fa4b-11e8-8535-8de9c1e1cf47.png)

Don't forget to reboot and then you can install python-binance via pip

**Comment by Roibal** [comment]
Thank you very kindly for the write-up!!
