### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1221328** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#21]
BinanceTriArbTrader.py
Everything installed.
Correct, working, new Binance API keys in BinanceKeys.py.

'\nExchange Status: ', {u'msg': u'normal', u'status': 0})
[]
LOADING BALANCES FROM BINANCE

FAILURE INITIALIZE

Restarting

**Comment by Roibal** [comment]
@1221328 - I have updated the 'TriArbTrader.py' bot to print out the error, and it's much better for debugging. Please use updated code to see proper error printing to the screen , post here and we will be able to identify the problem better.
