### ISSUE TITLE
Error: "No module named 'ccxt'"

### ISSUE THREAD

**Issue by DrJones55** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#23]
I did all the steps to get the binance bot installed from your step by step Youtube video and went to run a bot and was given this at the bottom of Pycharm.

  File "C:/Users/davey/Desktop/python-binance-master/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/Crypto-Trading-Bots/Advanced_Cryptocurrency_Trading_Bot.py", line 27, in <module>
    import ccxt
ModuleNotFoundError: No module named 'ccxt'

Process finished with exit code 1

**Comment by 1221328** [comment]
sudo apt install ccxt

**Comment by 1221328** [comment]
I do not think.

**Comment by amitkalo** [comment]
what about win10 users? what should do?

**Comment by keyvin-wei** [comment]
what should I do? Im win10 python 3.7.3,allredy install cctx1.0.0,but still No module named 'ccxt',help me!!
