### ISSUE TITLE
Working Bot

### ISSUE THREAD

**Issue by 1221328** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#26]
Hello again. The only one bot that I was able to run was this one CryptoTriangularArbitrageBinanceBot.py but which is not trading in reality. I would suggest to make only one version of the bot and fix all these issues.

**Comment by 1221328** [comment]
Okay. I was also able to run BinanceTriArbTrader.py but always lags and shows FAILURE INITIALIZE and restarts at this point.

**Comment by 1221328** [comment]
https://share.icloud.com/photos/0okUhWpdpJ7xuxgqmfAK2RFkg

**Comment by 1221328** [comment]
Let me know when you read it, please.

**Comment by JohnyDoe19** [comment]
Any news?

**Comment by 1221328** [comment]
Does not trade.

**Comment by Roibal** [comment]
Hi all and thank you for your questions. The Trader bot will in fact trade, however, most likely the fees are too high for a profitable trade (and therefore it will not trade). Profitable Triangular Arbitrage Opportunities are VERY rare, generally requires optimizing your connection and AWS hosting, as well as requires higher Binance VIP level.

**Comment by Roibal** [comment]
I added a fix to the Trader so that it will properly display error messages - if possible update your bot and post the new error message.
