### ISSUE TITLE
Python 2.7 ending 2020

### ISSUE THREAD

**Issue by Lukeday3179** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#33]
Hey mate I tried to run the bot but when I tried to install Project interpreter and it says that the software will end in Jan 2020 and wont be maintained. It says to upgrade package.

Please help.

Luke

**Comment by oliver-zehentleitner** [comment]
this means, you are using python2.x which is deprecated.

use python3.x instead.

**Comment by Lukeday3179** [comment]
Thanks mate.

**Comment by Lukeday3179** [comment]
You wouldn't know where I could get my hands on python 3?

**Comment by oliver-zehentleitner** [comment]
In general here https://www.python.org/downloads/
On linux i would use the package manager of the used distribution. (apt, yum, ...)
Depending of your needs it could be smart to use anaconda: https://www.anaconda.com/distribution/

**Comment by Lukeday3179** [comment]
All his scripts are written in Pythin 2.7, How do I update his scripts to the new python 3.7.3?

**Comment by cclauss** [comment]
@Lukeday3179 Did you get Python 3 working?  If so, can we close this issue?  If not, are you on Windows, Mac, Linux?

**Comment by Lukeday3179** [comment]
Hi I have not, I am using Mac. If you could give me directions on what to
do I will do the rest.

Thanks

Luke

**Comment by cclauss** [comment]
Open a terminal and type:
$ __sw_vers__
$ __brew info python__

What do you see?

**Comment by Lukeday3179** [comment]
Last login: Fri Jun 28 20:42:25 on console

  [Restored 17 Jul 2019 at 4:48:50 pm]

Last login: Mon Jul 15 14:58:31 on console

(base) Lukes-MBP:~ lukeday$

(base) Lukes-MBP:~ lukeday$ $sw_vers

(base) Lukes-MBP:~ lukeday$ $brew info python



















File: *manpages*,  Node: python,  Up: (dir)


PYTHON(1)
PYTHON(1)


NAME

       python  - an interpreted, interactive, object-oriented programming
lan-

       guage


SYNOPSIS

       python [ -B ] [ -d ] [ -E ] [ -h ] [ -i ] [ -m module-name ]

              [ -O ] [ -OO ] [ -R ] [ -Q argument ] [ -s ] [ -S ] [ -t ] [
-u

       ]

              [ -v ] [ -V ] [ -W argument ] [ -x ] [ -3 ] [ -?  ]

              [ -c command | script | - ] [ arguments ]


DESCRIPTION

       Python is an interpreted, interactive, object-oriented programming
lan-

       guage that combines remarkable power with very clear  syntax.   For
an

       introduction  to  programming  in Python, see the Python Tutorial.
The

       Python Library Reference documents built-in and  standard  types,
con-

       stants,  functions  and  modules.  Finally, the Python Reference
Manual

       describes the syntax and semantics of the  core  language  in
(perhaps

-----Info: (*manpages*)python, 353 lines
--Top----------------------------------

**Comment by Lukeday3179** [comment]
Hey mate, if you sent me an update zip of the bot I would e able to get my
api keys and do the rest.
Any chance we can do this?

Thanks

Luke

**Comment by cclauss** [comment]
Don't type the __$__ and try again.

**Comment by Lukeday3179** [comment]
Last login: Wed Jul 17 17:00:10 on ttys000

(base) Lukes-MBP:~ lukeday$ sw_vers

ProductName: Mac OS X

ProductVersion: 10.14.4

BuildVersion: 18E226

(base) Lukes-MBP:~ lukeday$ brew info python

-bash: brew: command not found

(base) Lukes-MBP:~ lukeday$

**Comment by cclauss** [comment]
$ xcode-select --install  # don't type the $
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew install python

**Comment by Lukeday3179** [comment]
==> *Summary*

🍺  /usr/local/Cellar/sqlite/3.28.0: 11 files, 3.7MB

==> *Installing python dependency: **xz*

==> *Downloading
https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar
<https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar>.*

==> *Downloading from
https://akamai.bintray.com/01/010667293df282c8bceede3bcd369
<https://akamai.bintray.com/01/010667293df282c8bceede3bcd369>*

########################################################################
100.0%

==> *Pouring xz-5.2.4.mojave.bottle.tar.gz*

🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB

==> *Installing **python*

==> *Downloading
https://homebrew.bintray.com/bottles/python-3.7.4.mojave.bottle
<https://homebrew.bintray.com/bottles/python-3.7.4.mojave.bottle>.*

==> *Downloading from
https://akamai.bintray.com/81/81fc6e5914a16387bd09387ce08e9
<https://akamai.bintray.com/81/81fc6e5914a16387bd09387ce08e9>*

########################################################################
100.0%

==> *Pouring python-3.7.4.mojave.bottle.tar.gz*

**Comment by Lukeday3179** [comment]
Still working

**Comment by Lukeday3179** [comment]
==> *python*

Python has been installed as

  /usr/local/bin/python3


Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to

`python3`, `python3-config`, `pip3` etc., respectively, have been installed
into

  /usr/local/opt/python/libexec/bin


If you need Homebrew's Python 2.7 run

  brew install python@2


You can install Python packages with

  pip3 install <package>

They will install into the site-package directory

  /usr/local/lib/python3.7/site-packages


See: https://docs.brew.sh/Homebrew-and-Python

(base) Lukes-MBP:~ lukeday$

**Comment by cclauss** [comment]
$ __python -V__ # Capital “V”
$ __python2 -V__
$ __python3 -V__

**Comment by Lukeday3179** [comment]
(base) Lukes-MBP:~ lukeday$ python -V

Python 3.7.3

(base) Lukes-MBP:~ lukeday$ python2 -V

-bash: python2: command not found

(base) Lukes-MBP:~ lukeday$ python3 -V

Python 3.7.3

(base) Lukes-MBP:~ lukeday$

**Comment by cclauss** [comment]
Fascinating...  brew poured Python 3.7.4 but you already had Python 3.7.3 installed.

You should add the following line at the bottom of your __~/.profile__ file
```
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
```
Quit the terminal and reopen it.  __python3 -V__ should now by Python 3.7.4

**Comment by Lukeday3179** [comment]
Please forgive me Im not sure how to do this.

You should add the following line at the bottom of your *~/.profile* file

export PATH="/usr/local/opt/python/libexec/bin:$PATH"

Can you tell where to go to update?

Thanks

Luke

**Comment by cclauss** [comment]
What text editor do you normally use?

**Comment by Lukeday3179** [comment]
I just use the one that is installed on my Laptop. Just a normal back
terminal screen.

**Comment by Lukeday3179** [comment]
Im in preferences trying to add the text.

**Comment by Lukeday3179** [comment]
I re-ran the python 3 V and its working.

**Comment by cclauss** [comment]
$ __python3 Roibal_BinanceBot.py__

If that works then please close this issue.

**Comment by Lukeday3179** [comment]
Last login: Wed Jul 17 18:12:05 on ttys000

(base) Lukes-MBP:~ lukeday$ python3 -V

Python 3.7.3

(base) Lukes-MBP:~ lukeday$

(base) Lukes-MBP:~ lukeday$ python3 Roibal_BinanceBot.py

python3: can't open file 'Roibal_BinanceBot.py': [Errno 2] No such file or
directory

(base) Lukes-MBP:~ lukeday$ $ python3 Roibal_BinanceBot.py

-bash: $: command not found

(base) Lukes-MBP:~ lukeday$

**Comment by cclauss** [comment]
Use __cd__ to change to the directory that has the __Roibal_BinanceBot.py__ file.

**Comment by Lukeday3179** [comment]
Clauss, I am some what an armature with this type of coding.

When use say "Use *cd* to change to the directory that has the
*Roibal_BinanceBot.py* file"
How do i do this?

Thanks

Luke

**Comment by cclauss** [comment]
$ __find ~ -name Roibal_BinanceBot.py__

**Comment by Lukeday3179** [comment]
find: /Users/lukeday/Library/Containers/com.apple.Home: Operation not permitted

find: /Users/lukeday/Library/Containers/com.apple.Safari: Operation
not permitted

find: /Users/lukeday/Library/Containers/com.apple.iChat: Operation not permitted

find: /Users/lukeday/Library/Containers/com.apple.mail: Operation not permitted

find: /Users/lukeday/Library/Containers/com.apple.news: Operation not permitted

find: /Users/lukeday/Library/Containers/com.apple.stocks: Operation
not permitted

find: /Users/lukeday/Library/PersonalizationPortrait: Operation not permitted

find: /Users/lukeday/Library/Metadata/CoreSpotlight: Operation not permitted

find: /Users/lukeday/Library/Metadata/com.apple.IntelligentSuggestions:
Operation not permitted

find: /Users/lukeday/Library/Cookies: Operation not permitted

find: /Users/lukeday/Library/Caches/CloudKit/com.apple.Safari:
Operation not permitted

find: /Users/lukeday/Library/Caches/com.apple.Safari: Operation not permitted

find: /Users/lukeday/Library/Caches/com.apple.Safari.SafeBrowsing:
Operation not permitted

/Users/lukeday/Downloads/Github/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/python-binance-master/examples/Crypto-Trading-Bots/Roibal_BinanceBot.py

(base) Lukes-MBP:~ lukeday$

(base) Lukes-MBP:~ lukeday$

**Comment by cclauss** [comment]
$ __cd /Users/lukeday/Downloads/Github/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/python-binance-master/examples/Crypto-Trading-Bots__
$ __python3 Roibal_BinanceBot.py__

**Comment by Lukeday3179** [comment]
/Users/lukeday/Downloads/Github/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/python-binance-master/examples/Crypto-Trading-Bots/Roibal_BinanceBot.py

(base) Lukes-MBP:~ lukeday$

(base) Lukes-MBP:~ lukeday$ cd
/Users/lukeday/Downloads/Github/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/python-binance-master/examples/Crypto-Trading-Bots

(base) Lukes-MBP:Crypto-Trading-Bots lukeday$ python3 Roibal_BinanceBot.py

Traceback (most recent call last):

  File "Roibal_BinanceBot.py", line 23, in <module>

    from binance.client import Client

ModuleNotFoundError: No module named 'binance'

(base) Lukes-MBP:Crypto-Trading-Bots lukeday$

**Comment by Lukeday3179** [comment]
So the issue was the cell library wouldn't work because I was using python
2.7, but we have gone through and installed python 3. If I am to run the
bot again will it run the updated python 3 and the cell library will work
when I run the bot?

Luke

**Comment by cclauss** [comment]
I think you should close this issue because you now have a working Python 3.7 on your Mac.  If you have other problems then open a new issue.

**Comment by Lukeday3179** [comment]
Ok then I will close the issue.

Thankyou for all your help its much appreciated.

Luke

**Comment by Lukeday3179** [comment]
Excellent support Thankyou
