### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by 1221328** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#4]
Traceback (most recent call last):
  File "CryptoTriangularArbitrageBinanceBot.py", line 24, in <module>
    from binance.client import Client
ImportError: No module named binance.client

**Comment by Roibal** [comment]
This error is caused when (I believe) you have not placed the "cryptotriangular..." (or any other bot) file in examples folder of Roibal/Python-Binance/ fork . 

I am putting this answer here in case anyone else runs into this problem at a later date.
