### ISSUE TITLE
no module named 'samplekeys'

### ISSUE THREAD

**Issue by mak3r** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#8]
I renamed the Crypto_Triangular_Arbitrage_Bot.py just for simplicity when running but I am getting an error with what appears to be a non-existent library. 

```
root@c3efcd8035e6:/app/python-binance# python examples/crypto-tri-arb-bot.py
Traceback (most recent call last):
  File "examples/crypto-tri-arb-bot.py", line 43, in <module>
    from samplekeys import keys, keys2, keys3, rkey
ModuleNotFoundError: No module named 'samplekeys'
```

I don't see the module in python-binance and it's not a standard python module installable via pip afaict.

**Comment by Roibal** [comment]
Hi my friend, samplekeys is a python file with the API keys in format to be loaded within the bot. I will try to find a blank one where I originally found idea.

**Comment by Roibal** [comment]
Also since you are not using any of these keys (for social media bot), you can simply comment out this line.

**Comment by Roibal** [comment]
SOLUTION: 

-If you want to 'tweet' out your charts/results, add samplekeys.py from https://github.com/Roibal/Reddit-Twitter-Social-Media-Bots 

-If you DO NOT want to 'tweet' out your charts/results (and simply save to computer), comment out #import sample keys and set 'Tweet' to 0/false in appropriate function call.
